#!/bin/bash

# Update package lists
yum update -y

# Install Node.js and npm
yum install -y nodejs npm
echo "Installing nodejs"

# Install project dependencies using npm
npm install
echo "Nodejs done"
